### ISSUE TITLE
impl_load_from_for_diesel assumes postgres backend

### ISSUE THREAD

**Issue by Adjective-Object** [davidpdrsn/juniper-eager-loading#16]
Hey, new to the rust-as-webserver environment so apoligies for any misunderstandings / incorrect assumptions.

It looks like [from the docs](https://docs.rs/juniper-eager-loading/0.2.0/juniper_eager_loading/macro.impl_load_from_for_diesel.html#what-gets-generated) that impl_load_from_for_diesel assumes that diesel is built with postgres support, since it inlines `use diesel::pg::expression::dsl::any;`

I'm using diesel with sqlite as my backend for a personal project. If I take the generated code and switch `.eq(any(ids))` for `.eq_any(ids)`, it builds.

Are there performance-based reasons to prefer `eq(any())` over `.eq_any` in the postgresql case, or would moving to `.eq_any` across the board be fine?

**Comment by Adjective-Object** [comment]
I'm happy to open a pull request for this if there's interest. I haven't worked with rust macros before and this seems like a simple way to dip my toes into it.

**Comment by davidpdrsn** [comment]
Ah yeah that’s true. I didn’t consider other backends there.

I’m not sure if there might be performance issues. I just followed the Diesel docs.

You’re welcome to submit a PR but I won’t have to look into it until the end of August as I’m on vacation now.
