### ISSUE TITLE
Question: How to map a table relationship?

### ISSUE THREAD

**Issue by youssefhabri** [davidpdrsn/juniper-eager-loading#44]
Hi

So, I' working with a database that has the following tables: `users` & `friendships`

And the graphql should is as follows:
```
"represents a single user account"
type User {
    [...]

    "all friends of the user"
    friends(first: Int=10, offset: Int=0): [User]
}
```

What would be the optimal way of handling this relationship (users -> friendships -> friends)?

**Comment by davidpdrsn** [comment]
You should be able to use a “has many through relationship”. Docs for that are here https://docs.rs/juniper-eager-loading/0.5.0/juniper_eager_loading/struct.HasManyThrough.html

**Comment by youssefhabri** [comment]
I didn't see that. Thanks, should work.
