### ISSUE TITLE
r2d2 compatibility for impl_load_from_for_diesel macro

### ISSUE THREAD

**Issue by tosti007** [davidpdrsn/juniper-eager-loading#46]
Currently when using the impl_load_from_for_diesel macros require the context object to implement a function: `fn db(&self) -> &Connection` with Connection being the correct database connection type. 
When using r2d2 for a postgres database a connection will be of type: `PooledConnection<ConnectionManager<PgConnection>>` which can be used for the load function.

To obtain one of these connections the `get` function should be called on the connection pool. However this returns an owned object instead of a reference. This breaks the, by the macro, created implementation since load requires a reference. 

Would there be a possible fix for this?

**Comment by davidpdrsn** [comment]
Hm not quite sure what your problem could be. It works fine for me:

```rust
#[macro_use]
extern crate diesel;

use diesel::prelude::*;
use diesel::r2d2::{ConnectionManager, Pool, PooledConnection};
use juniper_eager_loading::{impl_load_from_for_diesel_pg, prelude::*, LoadFrom};

table! {
    users (id) {
        id -> Integer,
        country_id -> Integer,
    }
}

table! {
    countries (id) {
        id -> Integer,
    }
}

#[derive(Queryable)]
struct User {
    id: i32,
    country_id: i32,
}

#[derive(Queryable)]
struct Country {
    id: i32,
}

impl_load_from_for_diesel_pg! {
    (
        error = diesel::result::Error,
        context = Context,
    ) => {
        i32 -> (users, User),
        i32 -> (countries, Country),
        User.country_id -> (countries.id, Country),
    }
}

struct Context {
    db: PooledConnection<ConnectionManager<PgConnection>>,
}

impl Context {
    fn db(&self) -> &PooledConnection<ConnectionManager<PgConnection>> {
        &self.db
    }

    // This also works and is what I would recommend
    // fn db(&self) -> &PgConnection {
    //     &self.db
    // }
}

fn load_from_pooled_connection() {
    let pool = create_db_connection_pool();
    let db = pool.get().unwrap();

    let ids = vec![1, 2, 3];

    let ctx = Context { db };

    // This compiles just fine
    User::load(&ids, &(), &ctx).unwrap();
}

fn create_db_connection_pool() -> Pool<ConnectionManager<PgConnection>> {
    todo!()
}
```

**Comment by tosti007** [comment]
In your example the PooledConnection is stored within the Context, but I would have liked to store the actual Pool within the context, like below. However having db() return a reference gives the problem of returning a local variable reference. 
```rust
pub struct Context {
    db: Pool<ConnectionManager<PgConnection>>,
}
impl Context {
    pub fn db(&self) -> PooledConnection<ConnectionManager<PgConnection>> {
        self.db.get().unwrap()
    }
}
```
However seeing your implementation should also work for me. I will save the connection instead. Thanks for the help!

**Comment by davidpdrsn** [comment]
I guess storing the pool itself within the context would require you get a new connection from the pool for each db query. That sounds like unnecessary overhead as opposed to getting one connection and reuse that throughout resolving a query. Is there any particular reason you want to store the pool inside the context?

Regarding things being Send/Sync. That isn't something I've played around with a lot myself. I'm currently using rocket and juniper without any async stuff. What are you trying to do that makes you run into this requirement?

**Comment by tosti007** [comment]
I think that taking a new connection and returning that connection as soon as possible back to the pool would be better in order to allow more multiple requests simultaneously. For example when the pool owns 8 connections the maximum number of simultaneous requests that can be processed is limited to 8 as well. 

I am using [actix web](https://actix.rs/) as my server library, which is async by nature. After trying a lot it turns out not to be a problem of the context object itself, but deep inside the schema object which uses the context object. 

Currently to solve my problem I wrote a simple macro myself. I assume it wouldn't be possible for the eager loading macro to check if the returned value is a reference or not. If it would be then that would be a great, if not then implementing it myself is the way to go.

**Comment by davidpdrsn** [comment]
Hm yeah I think making your own macro is the best way to go about it. Feel free to post it here for future people who might land upon this issue.

I'll close this for now but feel free to re-open if there is more add/discuss.

**Comment by tosti007** [comment]
I currently made my macro a bit too domain specific and quick and dirty that I think it's wise to not post it here.

For anyone stumbling across this issue and looking for a solution I would advice you to look at the [impl_load_from_for_diesel.rs file](https://github.com/davidpdrsn/juniper-eager-loading/blob/master/juniper-eager-loading-code-gen/src/impl_load_from_for_diesel.rs) and possibly [diesel's primary key function](http://docs.diesel.rs/diesel/query_source/trait.Table.html#tymethod.primary_key).
