### ISSUE TITLE
Required id field on model object of graphql object

### ISSUE THREAD

**Issue by tosti007** [davidpdrsn/juniper-eager-loading#48]
When defining a struct that derives `EagerLoading` the model object that contains the database data is required to have an `id` field. AFAIK there is currently no way of renaming this field. Could this be an option?

**Comment by davidpdrsn** [comment]
Yeah that makes sense 👍

**Comment by tosti007** [comment]
I spend today trying to implement it so I could send you a pull request, however this is a bit too large for me to oversee properly.

**Comment by davidpdrsn** [comment]
I’ll happily take a look at a PR 😊
