### ISSUE TITLE
Empty Mutation

### ISSUE THREAD

**Issue by DidierBoivin** [davidpdrsn/juniper-eager-loading#60]
Hi,
I don't understand how to define empty mutation with graphql_schema_from_file! 
Please help me

Didier

**Comment by davidpdrsn** [comment]
You simply just don't declare a mutation type when you declare you schema type. So

```graphql
schema {
  query: Query
}

type Query {
  # ...
}
```

Complete example: https://github.com/davidpdrsn/juniper-from-schema/blob/3aff741c3fd6adb53db4f2cabaed9c74b7b35f64/juniper-from-schema/tests/compile_pass/empty_mutations.rs
