### ISSUE TITLE
Performance with large Table

### ISSUE THREAD

**Issue by DidierBoivin** [davidpdrsn/juniper-eager-loading#62]
Hi,
Is there a way to improve the performance 
I only want to see the content  with a foreign key in another table 
It works with eager_load_all_children_for_each but takes a long time with large files 

Thanks for your help

**Comment by davidpdrsn** [comment]
The generated code shouldn't be causing any slowdowns. How many rows are loading? Maybe pagination would help? Can't say much more without more details.

**Comment by davidpdrsn** [comment]
I'm gonna close this issue for now. Feel free to re-open if you're able to provide more details.
