### ISSUE TITLE
Problem with Mutation 

### ISSUE THREAD

**Issue by DidierBoivin** [davidpdrsn/juniper-eager-loading#64]
Hi,
How can I use a mutation with the hasOne field ?
The compiler claims that the association has not completed for the Struct 

`#[derive(Clone, EagerLoading)]
#[eager_loading(context = Context, error = diesel::result::Error)]
pub struct Case {
    case: crate::models::Case,
    #[has_one(
        foreign_key_field = country_id,
        root_model_field = country,
        graphql_field = country,
    )]
    pub country: HasOne<Country>,
    #[has_one(
        foreign_key_field = user_id,
        root_model_field = user,
        graphql_field = user
    )]
    user: HasOne<User>,
    #[has_one(
        foreign_key_field = pathology_id,
        root_model_field = pathology,
        graphql_field = pathology
    )]
    pathology: HasOne<Pathology>,
    #[has_one(
        foreign_key_field = carbrand_id,
        root_model_field = carbrand,
        graphql_field = carbrand
    )]
    pub carbrand: HasOne<Carbrand>,
    #[has_one(
        foreign_key_field = contract_id,
        root_model_field = contract,
        graphql_field = contract
    )]
    contract: HasOne<Contract>,
    #[has_one(
        foreign_key_field = protocol_id,
        root_model_field = protocol,
        graphql_field = protocol
    )]
    protocol: HasOne<Protocol>,
    #[has_one(
        foreign_key_field = breakdowntype_id,
        root_model_field = breakdowntype,
        graphql_field = breakdowntype
    )]
    breakdowntype: HasOne<Breakdowntype>,
    #[has_one(
        foreign_key_field = damagetype_id,
        root_model_field = damagetype,
        graphql_field = damagetype
    )]
    damagetype: HasOne<Damagetype>
    
}
impl CaseFields for Case{
    fn field_country(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Country, Walked>,
    ) -> FieldResult<&Country> {
        self.country.try_unwrap().map_err(From::from)
    }
    fn field_user(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, User, Walked>,
    ) -> FieldResult<&User> {
        self.user.try_unwrap().map_err(From::from)
    }
    fn field_pathology(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Pathology, Walked>,
    ) -> FieldResult<&Pathology> {
        self.pathology.try_unwrap().map_err(From::from)
    }
    fn field_carbrand(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Carbrand, Walked>,
    ) -> FieldResult<&Carbrand> {
        self.carbrand.try_unwrap().map_err(From::from)
    }
    fn field_contract(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Contract, Walked>,
    ) -> FieldResult<&Contract> {
        self.contract.try_unwrap().map_err(From::from)
    }
    fn field_protocol(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Protocol, Walked>,
    ) -> FieldResult<&Protocol> {
        self.protocol.try_unwrap().map_err(From::from)
    }
    fn field_breakdowntype(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Breakdowntype, Walked>,
    ) -> FieldResult<&Breakdowntype> {
        self.breakdowntype.try_unwrap().map_err(From::from)
    }
    fn field_policyholder(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Country, Walked>,
    ) -> FieldResult<&Country> {
        self.country.try_unwrap().map_err(From::from)
    }
    fn field_damagetype(
        &self,
        _executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_, Damagetype, Walked>,
    ) -> FieldResult<&Damagetype> {
        self.damagetype.try_unwrap().map_err(From::from)
    }

    fn field_id(&self, _executor: &Executor<'_, Context>) -> std::result::Result<&std::string::String, juniper::FieldError> { 
        Ok(&self.case.id)
    }
    fn field_contract_serial_number(&self, _executor: &Executor<'_, Context>) -> std::result::Result<std::option::Option<&std::string::String>, juniper::FieldError> {
        Ok(Some(&self.case.contract_serial_number).unwrap().as_ref())
    }`

/*. 
`fn field_new_case( &self, 
        executor: &Executor<'_, Context>,
        _trail: &QueryTrail<'_,Case, Walked>,
        new_id: String,
        new_contract_serial_number: Option<String>,
        new_place_of_damage: Option<String>,
        new_valid_from: Option<String>,
        new_valid_to: Option<String>,
        new_case_creation_date: String,
        new_insurance_company: Option<String>,
        new_foreign_case_number: Option<String>,
        new_city_case: Option<String>, 
        new_zipcode_case: Option<String>,
        new_requestor_case: Option<String>,
        new_telephone_case: Option<String>,
        new_distance_case: Option<i32>,
        new_destination_case: Option<String>,
        new_alert_message: Option<String>,
        new_contract_checking: String,
        new_case_file: Option<String>,
        new_model_name: Option<String>,
        new_breakdown_description: Option<String>,
        new_place_immobilisation: Option<String>,
        new_registration_date: Option<String>,
        new_gearbox: String,
        new_fuel_type: String,
        new_license_plate_number: String,
        new_dealership: Option<String>, 
        new_coverage_limit: Option<String>,
        new_car_serial_number: Option<String>,
        new_civility: String,
        new_date_of_birth: Option<String>,
        new_medical_center_address: Option<String>,
        new_pathology_type: Option<String>,
        new_doctor: Option<String>, 
        new_telephone: Option<String>,
        new_hospitalisation_date: Option<String>,
        new_medical_information: Option<String>,
        new_medical_comments: Option<String>,
        new_last_name: String,
        new_first_name: Option<String>,
        new_cell_phone: Option<String>,
        new_home_phone: Option<String>,
        new_professional_phone: Option<String>,
        new_home_address: Option<String>,
        new_city: Option<String>,
        new_zipcode: Option<String>,
        new_destination: Option<String>,
        new_return_date: Option<String>,
        new_number_passagers: Option<i32>,
        new_carbrand_id: i32,
        new_breakdowntype_id: i32,
        new_contract_id: i32,
        new_country_id: String,
        new_pathology_id: String,
        new_policyholder_id: String,
        new_protocol_id: i32,
        new_damagetype_id: i32,
        new_user_id: i32
    ) -> std::result::Result<Case, FieldError>{
        let ctx = executor.context();
        use diesel::prelude::*;
        use crate::schema::myapp_case::dsl::*;
        let mut _result = myapp_case.filter(id.eq(&id)).load::<models::Case>(&ctx.pool.get().unwrap());
        
        let _number_of_records =
                match _result{
                    Ok(_result) =>  _result.len(),
                    Err(_e) =>  0
        };
        //let dt = NaiveDate::from_ymd(2020, 3, 1).and_hms_milli(0, 0, 0, 0);
        //let time = NaiveTime::from_hms_milli(0, 0, 0, 0);
        let new_date_valid_from = Some(NaiveDate::parse_from_str(&new_valid_from.unwrap(), "%Y-%m-%d").unwrap());
        let new_date_valid_to = Some(NaiveDate::parse_from_str(&new_valid_to.unwrap(), "%Y-%m-%d").unwrap());
        
        let new_registration_date = Some(NaiveDate::parse_from_str(&new_registration_date.unwrap(), "%Y-%m-%d").unwrap());
        
        let new_date_of_birth = Some(NaiveDate::parse_from_str(&new_date_of_birth.unwrap(), "%Y-%m-%d").unwrap());
        
        let new_hospitalisation_date = Some(NaiveDate::parse_from_str(&new_hospitalisation_date.unwrap(), "%Y-%m-%d").unwrap());
        let new_return_date = Some(NaiveDate::parse_from_str(&new_return_date.unwrap(), "%Y-%m-%d").unwrap());
        
        
        //let new_case_naive_date_creation_date = NaiveDate::parse_from_str(&new_valid_to.unwrap(), "%Y-%m-%d").unwrap();
        //let new_case_naive_date_creation_date_time  = new_case_naive_date_creation_date.and_hms(9, 10, 11);
        
        //let dt = new_case_naive_date_creation_date_time.from_timestamp(61, 0, Utc);

        use chrono::prelude::{Local};

        let utc: DateTime<Utc> = Utc::now();       // e.g. `2014-11-28T12:45:59.324310806Z`
        let local: DateTime<Local> = Local::now(); // e.g. `2014-11-28T21:45:59.324310806+09:00`

        //println!("result country {:?}",&_number_of_records);
        
        let new_case = crate::models::NewCase { 
            id: new_id, 
            contract_serial_number: new_contract_serial_number,
            place_of_damage : new_place_of_damage,
            valid_from: new_date_valid_from,
            valid_to: new_date_valid_to,
            case_creation_date: utc,
            insurance_company: new_insurance_company,
            foreign_case_number: new_foreign_case_number,
            city_case: new_city_case,
            zipcode_case: new_zipcode_case,
            requestor_case : new_requestor_case, 
            telephone_case: new_telephone_case,
            distance_case: new_distance_case,
            destination_case: new_destination_case,
            alert_message: new_alert_message,
            contract_checking: new_contract_checking, 
            case_file: new_case_file,
            model_name: new_model_name,
            breakdown_description: new_breakdown_description,
            place_immobilisation: new_place_immobilisation,
            registration_date: new_registration_date,
            gearbox: new_gearbox,
            fuel_type: new_fuel_type,
            license_plate_number: new_license_plate_number,
            dealership: new_dealership,
            coverage_limit: new_coverage_limit,
            car_serial_number: new_car_serial_number,
            civility: new_civility,
            date_of_birth: new_date_of_birth,
            medical_center_address: new_medical_center_address,
            pathology_type: new_pathology_type,
            doctor: new_doctor,
            telephone: new_telephone,
            hospitalisation_date: new_hospitalisation_date,
            medical_information: new_medical_information,
            medical_comments: new_medical_comments,
            last_name: new_last_name,
            first_name: new_first_name,
            cell_phone: new_cell_phone,
            home_phone: new_home_phone,
            professional_phone: new_professional_phone,
            home_address: new_home_address,
            city: new_city,
            zipcode: new_zipcode,
            destination: new_destination,
            return_date: new_return_date,
            number_passagers: new_number_passagers,
            carbrand_id: new_carbrand_id,
            breakdowntype_id: new_breakdowntype_id,
            contract_id: new_contract_id,
            country_id: new_country_id,
            pathology_id: new_pathology_id,
            policyholder_id: new_policyholder_id,
            protocol_id: new_protocol_id,
            damagetype_id: new_damagetype_id,
            user_id: new_user_id,
            
        };
        
        let record_of_case_table : models::Case;
        
        if _number_of_records == 0 {
            let new_case_to_insert: crate::models::Case = diesel::insert_into(crate::schema::myapp_case::table)
                .values(&new_case)
                .get_result(&ctx.pool.get().unwrap())
                .expect("Error saving new post");
                record_of_case_table = new_case_to_insert; 
            
            }else{
                let case_to_update = diesel::update(myapp_case.filter(id.eq(new_case.id)))
                    .set(&new_case)
                    .get_result(&ctx.pool.get().unwrap())
                    .expect("Error saving new post");
                record_of_case_table = case_to_update;
            }
            
        
        Ok(Case{case: record_of_case_table,carbrand} )`

     |                                            ^^^^^^^^ not found in this scope
missing fields `breakdowntype`, `contract`, `country` and 4 other fields in initializer of `graphql::Case`
    --> src/graphql.rs:1912:12
     |
1912 |         Ok(Case{case: record_of_case_table,carbrand} )
     |            ^^^^ missing `breakdowntype`, `contract`, `country` and 4 other fields

error: aborting due to 2 previous errors

**Comment by davidpdrsn** [comment]
Would you mind formatting the code with back ticks? Its hard to read currently.

**Comment by DidierBoivin** [comment]
Hey,
here is the file 
https://github.com/DidierBoivin/Rust/blob/main/graphql.rs
The problem is to return a graphql  type ( line 1902) with HasOne attached with the Struct Case ( line 586 until 636)
How can I use the HasOne method or should I use the juniper_eager_loading 
I don't know how to do it 
Thanks

**Comment by davidpdrsn** [comment]
Sorry for the harshness but its difficult for me to help you without code that I can actually compile and play around with myself. If you make a minimal, reproducible example (eg a small repo that I clone and `cargo check` to see the error) I'll happily help. That 2000 line file doesn't tell me much.

**Comment by DidierBoivin** [comment]
Hi,Thank you for your reply
I have just found a solution which is to add eager_load_all_children to the Struct and it works correctly 
The mutation is working correctly

Thanks again

let ctx = executor.context();
        
        let case_models = models::Case::get_case(record_of_case_table.id, ctx)?;

        let mut cases = Case::from_db_models(&case_models);
        Case::eager_load_all_children_for_each(&mut cases,&case_models,ctx,_trail)?;
        
        let case_cloned =cases[0].clone();
        
        Ok(case_cloned)

**Comment by davidpdrsn** [comment]
Awesome! Happy that you found a solution 👍

**Comment by DidierBoivin** [comment]
Is there other solution that juniper_eager_loading_all_children to create the grapqhl Struct 
My solution is to retrieve the record  from Diesel after saving it then render the record after juniper_eager_loading _all_children

Didier

**Comment by davidpdrsn** [comment]
No not currently.
