### ISSUE TITLE
Integrating Identification Juniper

### ISSUE THREAD

**Issue by DidierBoivin** [davidpdrsn/juniper-eager-loading#65]
Hey,
Did you have some guides for implementing identification 
I don't understand how to do that

**Comment by davidpdrsn** [comment]
What do you mean by "identification"?

**Comment by DidierBoivin** [comment]
Hey,
I want to add jsonwebtoken to protect my graphql server

**Comment by davidpdrsn** [comment]
This doesn't really have anything to do with juniper-eager-loading. There are lots of tutorials on the web for doing JWT authentication. I have personally used https://crates.io/crates/jsonwebtoken.

Gonna close this as its not related to juniper-eager-loading.
