### ISSUE TITLE
Support HasMany with Option/nullable foreign key 

### ISSUE THREAD

**Issue by kiljacken** [davidpdrsn/juniper-eager-loading#7]
I have a schema that looks something like the following:
```
schema { .. }
type Query { .. }
type Mutation { .. }
type ArtistUser {
    id: ID! @juniper(ownership: "owned")
    name: String!
}

type Album {
    id: ID! @juniper(ownership: "owned")
    name: String!
    artist: ArtistUser!
    tracks: [Track!]!
}

type Track {
    id: ID! @juniper(ownership: "owned")
    name: String!
    artist: ArtistUser!
    album: Album,
}
```

Having derived eager loading for all the graphql types, and LoadFrom for the models, I get an error attempting to compare `i64 == Option<i64>` because the foreign key field on a track is optional.

Looking at the codegen for is_child shows [where the issue occurs](https://github.com/davidpdrsn/juniper-eager-loading/blob/master/juniper-eager-loading-code-gen/src/derive_eager_loading.rs#L413). I'd love to provide the needed functionality in a PR, but could use some input on how you'd want it implemented.

Thanks.

**Comment by kiljacken** [comment]
Whoops i was a little quick on the enter, actual issue text will follow in a bit

**Comment by davidpdrsn** [comment]
Thanks for opening an issue! Cool that you're trying this out 😊

I think is something we should definitely support! Can you try to implement `EagerLoadChildrenOfType` manually for this one field and then post your code here? An example of how to implement the trait manually can be found here https://docs.rs/juniper-eager-loading/0.1.0/juniper_eager_loading/trait.EagerLoadChildrenOfType.html#manual-implementation

Right now I can't quite imagine how exactly the implementation will look, but it might turn out to be pretty straight forward.

**Comment by davidpdrsn** [comment]
Ah wait sorry that might not be possible. `HasMany` or `HasManyThrough` might not work at all for this. Not quite sure 🤔

I'll investigate it this week.

**Comment by kiljacken** [comment]
From what I can gather from a quick manual implementation of `EagerLoadChildrenOfType` the only change from the ordinary HasMany generation I need is in `is_child_of`:
```diff
 fn is_child_of(node: &Self, child: &(Track, &())) -> bool {
-     node.album.id == (child.0).track.album_id
+     Some(node.album.id) == (child.0).track.album_id
 }
```

So it should be fairly easily doable, I was mainly wondering whether it made more sense as an option on HasMany or as a seperate type :)

**Comment by davidpdrsn** [comment]
Great!

I've thought about this as well. I think using `HasMany` is fine since the default is an empty vec already. I guess that also makes sense in this case.

**Comment by kiljacken** [comment]
Cool! I'll drop a PR soon-ish then :)

**Comment by davidpdrsn** [comment]
Thanks 🎊
